---
- name: Merge provided configuration with device configuration
  ios_vlans:
    config:
    - name: Endpoints
      vlan_id: 10
      state: active
      shutdown: disabled
    - name: Guest
      vlan_id: 20
      state: active
      shutdown: disabled
    - name: IoT
      vlan_id: 30
      state: active
      shutdown: disabled
    state: merged

- name: Gather VLANs
  ios_vlans:
    config:
    state: gathered
