---
- name: Abort if not IOS
  fail:
    msg: "Aborting. {{ ansible_host }} does not appear to be of type IOS"
  when: ansible_net_iostype != 'IOS'

- name: Abort if IOS version is not supported by this task
  fail:
    msg: "Aborting. {{ ansible_net_version }} is not supported in tasks/vars/main.yml"
  when: ansible_net_version not in supported_versions

- name: Merge group or host var VLANs with target
  ios_vlans:
    config:
    - name: "{{ item.name }}"
      vlan_id: "{{ item.id }}"
      state: active
    state: merged
  loop: "{{ my_vlans }}"

- name: Gather VLANs post merge
  ios_vlans:
    config:
    state: gathered
  register: vlan_out

- name: Print VLAN list
  debug:
    var: vlan_out
