---
- name: Merge provided configuration with device configuration
  ios_vlans:
    config:
    - name: "{{ item.name }}"
      vlan_id: "{{ item.id }}"
      state: active
    state: merged
    with_list: "{{ my_vlans }}"

- name: Gather VLANs
  ios_vlans:
    config:
    state: gathered
    register: vlan_out

- name: Print gathered VLANs
  debug:
    msg: vlan_out
