---
- name: Pre configuration checks
  fail:
    msg: "abort"
  when: (ansible_net_iostype != 'IOS') and (not supported_version[ansible_net_version])

- name: Merge group or host var VLANs with target
  ios_vlans:
    config:
    - name: "{{ item.name }}"
      vlan_id: "{{ item.id }}"
      state: active
    state: merged
  loop: "{{ my_vlans }}"

- name: Gather VLANs post merge
  ios_vlans:
    config:
    state: gathered
  register: vlan_out

- name: Print VLAN list
  debug:
    var: vlan_out
