---
- name: Merge provided configuration with device configuration
  ios_vlans:
    config:
    - name: "{{ my_vlans.name }}"
      vlan_id: "{{ my_vlans.id }}"
      state: active
    state: merged
    with_items: {{ my_vlans }}

- name: Gather VLANs
  ios_vlans:
    config:
    state: gathered
    register: vlan_out

- name: Print gathered VLANs
  debug:
    msg: vlan.out
