---
- name: Configure the login banner
  ios_banner:
    banner: login
    text: "{{ lookup('file', './login-banner') }}"
    state: present

- name: Configure the motd banner
  ios_banner:
    banner: exec
    text: "Begin session with {{ ansible_host }} version {{ ansible_net_version }}"
    state: present