---
- name: Configure the login banner
  cisco.ios.ios_banner:
    banner: login
    text: "{{ lookup('file', './login-banner') }}"
    state: present

- name: Configure the motd banner
  cisco.ios.ios_banner:
    banner: exec
    text: "Begin session with {{ hostname_alias | default( inventory_hostname ) }} at {{ ansible_host }}"
    state: present
