---
- name: "Configure hostname {{ inventory_hostname }}"
  cisco.ios.ios_hostname:
    config:
      hostname: "{{ inventory_hostname }}"
    state: merged

- name: Save running to startup when modified
  ios_config:
    save_when: modified