---
- name: "Configure hostname {{ hostname_alias | default( inventory_hostname ) }}"
  cisco.ios.ios_hostname:
    config:
      hostname: "{{ hostname_alias | default( inventory_hostname ) }}"
    state: merged
