---
- name: "Configure hostname {{ hostname_alias | inventory_hostname }}"
  cisco.ios.ios_hostname:
    config:
      hostname: "{{ hostname_alias | inventory_hostname }}"
    state: merged

- name: Save running to startup when modified
  cisco.ios.ios_config:
    save_when: modified