---
- name: Set hostname {{ hostname_alias | default( inventory_hostname ) }}
  ios_hostname:
    config:
      hostname: "{{ hostname_alias | default( inventory_hostname ) }}"
    state: merged

- name: Save running to startup when modified
  ios_config:
    save_when: modified